<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <GenerateResourceNever>true</GenerateResourceNever>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.5.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3912.50" />
    <PackageReference Include="System.Speech" Version="10.0.6" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Helpers\*.resx" />
    <EmbeddedResource Remove="Helpers\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <!-- Ensure no .resx files are treated as embedded resources or copied to output -->
    <EmbeddedResource Remove="**\*.resx" />
    <None Include="**\*.resx">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Helpers\CompteHistoire.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Helpers\WriteAnything.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Helpers\VerbeConjuger.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Helpers\AnimauxMFP.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Helpers\ABC.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Helpers\NombreRomain.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Helpers\Nombre.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="WebView2s\Prononciation.cs" />
  </ItemGroup>
</Project>